# We-Birds Template - GitHub Actions Publish
# Version: 1.0.0
# Last Updated: 2025-11-05
#
# This workflow uses Trusted Publishing to publish to PyPI.
# No API tokens needed!
#
# Setup: https://docs.pypi.org/trusted-publishers/

name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for Trusted Publishing (OIDC)
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # Note: No token needed! GitHub generates short-lived OIDC token
      # Make sure Trusted Publisher is configured on PyPI:
      # https://pypi.org/manage/account/publishing/
